# Test against this version of Node.js
environment:
  
  matrix:
    nodejs_version: "8"
  
    # Install scripts.
    install:        
        - ps: Install-Product node $env:nodejs_version

        - npm install
    test_script:
      - node --version
      - npm --version
      - npm test
    
    build: off
